services:
  mysql:
    image: mysql:8.0
    container_name: mysql_contenidor
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: elementos
      MYSQL_USER: usuario_db
      MYSQL_PASSWORD: password_db
    volumes:
      - datos_mysql:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: backend_contenidor
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    command: sh -c "./wait-for-it.sh mysql_contenidor:3306 --timeout=60 --strict -- php -S 0.0.0.0:8000"

  frontend:
    build: ./frontend
    container_name: frontend_contenidor
    depends_on:
      - backend
    ports:
      - "8080:8080"

  phpmyadmin:
    image: phpmyadmin
    container_name: adminMySQL_contenidor
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql_contenidor
    ports:
      - "8081:80"

volumes:
  datos_mysql:
